Repository ProgramistaZpolski/nougat-max, pull requests merged in 2020-04, with the labels that each got.

#2 wygląd komendy pozwij
  komendy/pozwij.js
Labels: enhancement

#3 userinfo
  komendy/userinfo.js
Labels: enhancement

#8 najnowsza wersja ZabijSięDB
  komendy/8ball.js
  komendy/darmowepociagi.js
  komendy/fajnypociag.js
  komendy/help.js
  komendy/statki.js
  komendy/userinfo.js
  komendy/wyscig-easy.js
  komendy/wyscig-hard.js
  komendy/wyscigpociagow.js
  komendy/zjedz.js
  zabij-sie-db.js
Labels: ZabijSięDB

#19 Najnowsze śmieci
  bot.js
  komendy/8ball.js
  komendy/fajnypociag.js
  komendy/money.js
  komendy/orangesupport.js
  komendy/pay.js
  komendy/sms.js
  komendy/wyscigpociagow.js
Labels: bug, documentation, enhancement

#20 Nowe zabijsiedb
  zabij-sie-db.js
Labels: ZabijSięDB

#23 Aktualizacja komendy help
  komendy/help.js
Labels: documentation
